# PhaseZero Windows VM - VirtioFS + SPICE WebDAV + RDP Provisioning
# Place this bundle in the exchange directory and run as Administrator in the guest.
# Requires: Windows 10 22H2+ or Windows 11, PowerShell 5.1+, internet for driver downloads.

param(
    [switch]$SkipVirtioFS,
    [switch]$SkipSpiceWebDAV,
    [switch]$SkipRDP,
    [switch]$Offline,
    [string]$BundlePath = "$PSScriptRoot"
)

$PZ_LOG_DIR = "$env:ProgramData\PhaseZero"
$null = New-Item -ItemType Directory -Force -Path $PZ_LOG_DIR
$LOG = "$PZ_LOG_DIR\provisioning.log"
$PZ_ROOT_REG = "HKLM:\Software\PhaseZero"

function Write-Log {
    param([string]$Message)
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$ts $Message" | Out-File -FilePath $LOG -Encoding utf8 -Append
    Write-Host "$ts $Message"
}

function Get-VendorMsi {
    param([string]$FileName)
    $path = Join-Path $BundlePath $FileName
    if (Test-Path $path) { return $path }
    return $null
}

function Install-VirtioFS {
    Write-Log "=== Installing VirtioFS + WinFsp ==="
    $tmpDir = "$env:TEMP\pz-virtiofs"
    $null = New-Item -ItemType Directory -Force -Path $tmpDir
    try {
        $winfspMsi = Get-VendorMsi "winfsp-2.0.23075.msi"
        $virtioMsi = Get-VendorMsi "virtio-win-gt-x64.msi"
        if (-not $winfspMsi -and -not $Offline) {
            Write-Log "Downloading WinFsp from GitHub..."
            $winfspMsi = "$tmpDir\winfsp.msi"
            Invoke-WebRequest -Uri "https://github.com/winfsp/winfsp/releases/download/v2.0/winfsp-2.0.23075.msi" -OutFile $winfspMsi -UseBasicParsing
        }
        if (-not $virtioMsi -and -not $Offline) {
            Write-Log "Downloading Virtio-win Guest Tools from Fedora People..."
            $virtioMsi = "$tmpDir\virtio-win-gt-x64.msi"
            Invoke-WebRequest -Uri "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win-gt-x64.msi" -OutFile $virtioMsi -UseBasicParsing
        }
        if (-not $winfspMsi) { throw "WinFsp MSI not found (use -Offline only when MSIs are vendored in bundle)" }
        if (-not $virtioMsi)  { throw "Virtio-win MSI not found (use -Offline only when MSIs are vendored in bundle)" }
        Write-Log "Installing WinFsp..."
        Start-Process msiexec.exe -ArgumentList "/i `"$winfspMsi`" /qn /norestart" -Wait -NoNewWindow
        Write-Log "Installing Virtio-win Guest Tools (includes VirtioFS)..."
        Start-Process msiexec.exe -ArgumentList "/i `"$virtioMsi`" /qn /norestart ADDLOCAL=VirtioFSService" -Wait -NoNewWindow
        Write-Log "VirtioFS + WinFsp installed"
    } finally {
        Remove-Item -Recurse -Force $tmpDir -ErrorAction SilentlyContinue
    }
}

function New-VirtioFSMounts {
    Write-Log "=== Creating VirtioFS mount points ==="
    $mounts = @(
        @{Tag="hosthome"; Drive="Z:"},
        @{Tag="exchange"; Drive="Y:"},
        @{Tag="sdcard"; Drive="X:"},
        @{Tag="removable"; Drive="W:"},
        @{Tag="media"; Drive="V:"},
        @{Tag="mnt"; Drive="U:"}
    )
    $serviceName = "PhaseZeroVirtioFS"
    $psScript = "$env:ProgramData\PhaseZero\mount-virtiofs.ps1"
    $null = New-Item -ItemType Directory -Force -Path "$env:ProgramData\PhaseZero"
    @"
# Auto-generated by PhaseZero provisioning
`$mounts = @(
@{Tag='hosthome';Drive='Z:'},
@{Tag='exchange';Drive='Y:'},
@{Tag='sdcard';Drive='X:'},
@{Tag='removable';Drive='W:'},
@{Tag='media';Drive='V:'},
@{Tag='mnt';Drive='U:'}
)
`$sockDir = "\\?\pipe\virtiofs"
foreach (`$m in `$mounts) {
    `$sock = Join-Path `$sockDir "`$(`$m.Tag)"
    `$drive = `$m.Drive
    if (-not (Test-Path `$drive)) {
        `$proc = Start-Process -FilePath "virtiofs.exe" -ArgumentList "--socket-path=`$sock --mount-point=`$drive" -NoNewWindow -PassThru
        Write-Host "virtiofs mounted `$(`$m.Tag) -> `$drive (PID `$(`$proc.Id))"
    } else {
        Write-Host "virtiofs `$drive already mounted"
    }
}
"@ | Out-File -FilePath $psScript -Encoding utf8
    Write-Log "Creating scheduled task for VirtioFS mounts..."
    $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$psScript`""
    $trigger = New-ScheduledTaskTrigger -AtStartup
    $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
    $null = Register-ScheduledTask -TaskName $serviceName -Action $action -Trigger $trigger -Principal $principal -Force
    Write-Log "Scheduled task $serviceName created"
}

function Install-SpiceWebDAV {
    Write-Log "=== Installing SPICE WebDAV daemon ==="
    $tmpDir = "$env:TEMP\pz-spice"
    $null = New-Item -ItemType Directory -Force -Path $tmpDir
    try {
        $msi = Get-VendorMsi "spice-webdavd-x64-latest.msi"
        if (-not $msi -and -not $Offline) {
            Write-Log "Downloading spice-webdavd..."
            $msi = "$tmpDir\spice-webdavd.msi"
            Invoke-WebRequest -Uri "https://www.spice-space.org/download/windows/spice-webdavd/spice-webdavd-x64-latest.msi" -OutFile $msi -UseBasicParsing
        }
        if (-not $msi) { throw "spice-webdavd MSI not found (use -Offline only when MSIs are vendored in bundle)" }
        Write-Log "Installing spice-webdavd..."
        Start-Process msiexec.exe -ArgumentList "/i `"$msi`" /qn /norestart" -Wait -NoNewWindow
        Write-Log "spice-webdavd installed"
    } finally {
        Remove-Item -Recurse -Force $tmpDir -ErrorAction SilentlyContinue
    }
}

function Enable-RdpShares {
    Write-Log "=== Enabling RDP drive redirection ==="
    $regPath = "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server"
    try {
        Set-ItemProperty -Path $regPath -Name "fSingleSessionPerUser" -Value 0 -Type DWord -Force
        Set-ItemProperty -Path "$regPath\WinStations\RDP-Tcp" -Name "fDisableAutoReconnect" -Value 0 -Type DWord -Force
        Write-Log "RDP session settings applied"
    } catch {
        Write-Log "WARN: RDP registry settings failed: $_"
    }
    $rdpDriveReg = "HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services"
    $null = New-Item -ItemType Directory -Force -Path $rdpDriveReg
    try {
        Set-ItemProperty -Path $rdpDriveReg -Name "fDisableCdm" -Value 0 -Type DWord -Force
        Set-ItemProperty -Path $rdpDriveReg -Name "fEnableDriveRedirection" -Value 1 -Type DWord -Force
        Write-Log "RDP drive redirection enabled (GPO)"
    } catch {
        Write-Log "WARN: RDP GPO settings failed: $_"
    }
    Write-Log "Restarting TermService..."
    Restart-Service TermService -Force -ErrorAction SilentlyContinue
    Write-Log "RDP shares configured"
}

function Write-Summary {
    $summary = @"
Provisioning Summary:
  VirtioFS:       $(-not $SkipVirtioFS)
  SPICE WebDAV:  $(-not $SkipSpiceWebDAV)
  RDP Shares:    $(-not $SkipRDP)
  Offline:       $Offline
  Bundle:        $BundlePath
  Log:           $LOG
"@
    Write-Log $summary
    $summary | Out-File -FilePath "$PZ_LOG_DIR\provisioning-summary.txt" -Encoding utf8
}

# Main
Write-Log "=== PhaseZero Windows VM Guest Provisioning ==="
Write-Log "Started at $(Get-Date)"

if (-not $SkipVirtioFS) {
    Install-VirtioFS
    New-VirtioFSMounts
}
if (-not $SkipSpiceWebDAV) {
    Install-SpiceWebDAV
}
if (-not $SkipRDP) {
    Enable-RdpShares
}

Write-Summary
Write-Log "Provisioning complete"
